### ISSUE TITLE
Read conditions from config file

### ISSUE THREAD

**Issue by prperold** [hans-wernerheuer/fresh_forecast#11]
Instead of hardcoded condition values for specific spots, rather read from some configuration.

https://github.com/hans-wernerheuer/fresh_forecast/blob/d5a2b0cc6413b92f4ecb880601738f56abcd2997/src/utils.py#L48

Maybe a good idea to start by reading from something like a yaml file. This could later change to a database.

Yaml example:

```yaml
'Bettys Bay':
    swell: 0.5
    wind: 5
'Pringle Bay':
    swell: 1.5
    wind: 10
```
Doesn't have to be exactly like that, just a suggestion.
